version: 2.1

orbs:
  docker: circleci/docker@3.1.1

# Reusable commands
commands:
  restore-dotnet:
    description: "Restore .NET dependencies"
    steps:
      - run:
          name: Restore .NET dependencies
          command: dotnet restore

  build-dotnet:
    description: "Build .NET project"
    parameters:
      project-path:
        type: string
        description: "Path to the project file"
    steps:
      - run:
          name: Build .NET project
          command: dotnet build << parameters.project-path >> --configuration Release --no-restore

  test-dotnet:
    description: "Run .NET tests"
    parameters:
      project-path:
        type: string
        description: "Path to the test project file"
    steps:
      - run:
          name: Run .NET tests
          command: dotnet test << parameters.project-path >> --configuration Release --no-build --verbosity normal

# Jobs using .NET SDK
jobs:
  build-test-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - restore-dotnet
      - build-dotnet:
          project-path: "ProductService/ProductService.csproj"
      - test-dotnet:
          project-path: "ProductService/ProductService.csproj"

# Jobs using Docker
jobs:
  build-test-docker:
    docker:
      - image: docker:24.0.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t productservice ./ProductService
      - run:
          name: Test Docker container
          command: |
            docker run --rm productservice dotnet test

# Workflows
workflows:
  version: 2
  build-test:
    jobs:
      - build-test-dotnet:
          name: build-test-dotnet-sdk
          filters:
            branches:
              only: main
      - build-test-docker:
          name: build-test-docker
          filters:
            branches:
              only: main
          requires:
            - build-test-dotnet-sdk

# Cache configuration
cache:
  paths:
    - ~/.nuget/packages
    - ProductService/bin
    - ProductService/obj 