name: Build & Deploy CartService

on:
  push:
    paths:
      - 'CartService/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: vasanthpr
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./CartService
          file: ./CartService/Dockerfile
          push: true
          tags: vasanthpr/cartservice:latest,vasanthpr/cartservice:${{ github.sha }} 